### ISSUE TITLE
Upgrade RVD workspace to use the new project naming convention

### ISSUE THREAD

**Issue by otsakir** [RestComm/RestComm-Core#530]
Project directories should be renamed to their respective Application SID. At the same time the Application record can be created if necessary. 

The task can be carried out when RVD starts.

**Comment by ghjansen** [comment]
Once this issue is strongly linked to #553 and they both form a dependency to another issues, they are been designed and will probably implemented together.
The following represents the current ideas for the design to migrate the naming convention and synchronisation of the projects to the Applications API, followed by a diagram that tries to illustrate the relationship between RVD and Restcomm through this new perspective.

**1 - Place the RVD projects migration inside Restcomm's bootstrap allowing it to directly manipulate workspace files and database records, executing as it follows:**
1.1 Check each project in the workspace, if the directory name represents a valid applicationSid skip, otherwise go to 1.2;
1.2 - Access Applications API and check if already exists an Application with this name and owner, if so get the applicationSid and go to 1.3, otherwise create a new Application, get the applicationSid and go to 1.3;
1.3 - Rename the project directory using the applicationSid obtained by contacting the Applications API;
1.4 - Check each IncomingPhoneNumber configured with one or more Application, and replace the application URL (provided by RVD) to its respective applicationSid;
1.5 - Check each Client configured with a Application, replacing the application URL (provided by RVD) to its respective applicationSid;

**2 - Change the way RVD list projects and use Applications API instead of reading directly from workspace, the same way will be done in AdminUI;**

**3 - Adapt RVD REST endpoints, so they will be able to operate using both project name or applicationSid. Main endpoints are: ProjectRestService, RvdController, RasRestService, DesignerRestService;**

**4 - Adapt RVD Applications API Synchronization, to work with applicationSid reference instead of project name;**

![530](https://cloud.githubusercontent.com/assets/1459428/11442705/c226264e-94fe-11e5-91ab-fa5341b5dbdd.png)

New ideas already on the way! :)

**Comment by ghjansen** [comment]
Synthesis from the past discussions on the new design proposals related to this issue:
* Creation of a new Workspace Manager SPI to handle different ways to store a RVD project (like MongoDB) rather than file system only;
* Adapt Restcomm bootstrap to execute the migration of RVD Projects once, accessing the workspace in a very specific way, only for migration purpose.

The image below approaches the final structure with the Workspace Manager SPI.

![530-3](https://cloud.githubusercontent.com/assets/1459428/11656069/d4e997e0-9d99-11e5-90bc-31e7dcc0d7ba.png)

**Comment by ghjansen** [comment]
The following diagram shows the behaviour of the migration executed in Restcomm bootstrap.

![migratoralgorithm-2](https://cloud.githubusercontent.com/assets/1459428/11759951/7865db50-a06e-11e5-9125-4f2e5413fbc4.png)

Important details about the algorithm:
* The name of the project is stored inside the 'state' file of the RVD project to avoid name loss if something went wrong during the migration;
* A new file called 'workspaceStatus' will be created inside the workspace to store the attribute 'namingMigrationSucceeded' that have the result of the migration process.

Because different errors can happen in different parts of the algorithm, its possible that Restcomm starts with only part of the workspace migrated, not migrated or completely migrated. So given those three possibilities I dont think as a good idea to have RVD UI and Admin UI requesting the applications list directly to Restcomm Applications REST API, since in case of the migration fails, maybe only part of the Projects turned into Applications.

Thinking in solutions about how RVD UI and AdminUI could obtain a consistent list of projects independently of the result of the migration, my current idea is:
1 - RVD UI and Admin UI request to RVD context the result of the migration executed by Restcomm;
2 - RVD context read the 'workspaceStatus' file and respond the result of the migration process;
3 - RVD UI and Admin UI stores the result of this request to not perform it again next time;
4 - If the response says the migration failed, both UIs keep requesting the project list to RVD (possible since the project name is stored inside the project), if the migration succeeded, both UIs can finally starts to use Restcomm Applications API.

The algorithm was though to be prepared to start from all the possible workspace states. Following, each workspace state and the behaviour of the algorithm:
* Not migrated -> Try to migrate
* Partially migrated -> Skip the migration work already done and continue from the failed projects
* Completely migrated -> Skip the entire migration execution

The number of details is a little big, so im possibly forgetting to mention something that could help understand, but ill post later if I remember of something. The commit to this modification is here: 2eb8d8dcb539e20438a4a681381fb60920cefd00

Thoughts? @otsakir @gvagenas

**Comment by ghjansen** [comment]
Closed via Pull Request #817.
