### ISSUE TITLE
When using LCM to modify a call, the media from the previous application continues to be heard together with the new application

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/RestComm-Core#834]
Scenario (tested with latest Docker image):
* Make a call from Restcomm to alice via REST and connect it with dial-conference application:
```
curl -k -X POST https://ACae6e420f425248d6a26948c17a9e2acf:0d01c95aac798602579fe08fc2461036@54.205.100.103/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26.json -d "From=%2B16175551212" -d "To=client:alice" -d "Url=https://54.205.100.103/restcomm/demos/dial/conference/dial-conference.xml"
```
* While the call is in progress and I hear the hold music send another REST request to modify the call and connect to hello-world application:
```
curl -k -X POST https://ACae6e420f425248d6a26948c17a9e2acf:0d01c95aac798602579fe08fc2461036@54.205.100.103/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26/CA3a563fda5c8d491684d5c680d58fb37c -d "Url=https://54.205.100.103/restcomm/demos/hello-world.xml"
```

The problem is that at that point I start hearing the hello-world announcement, while the conference music is still heard (like media for both applications are mixed together).

For logs and network traffic, please check: https://drive.google.com/file/d/0BwfD74mG87iMUFgzR1dOY1pPVkU/view?usp=sharing

**Comment by gvagenas** [comment]
Commit that closes this issue: https://github.com/RestComm/RestComm-Core/commit/2f367a38d41c8adc6bd4535a5a235d09a8b95da1

**Comment by gvagenas** [comment]
@hrosa For this issue I have ready a patch that properly setup signalling and media paths for the LCM call flow as reported from Antonis above.
As said, the media is ok with the prepared patch, and the sip client gets the announcements as expected.

Nevertheless I see an MGCP request to DLCX the initial bridge endpoint and I am not sure if this is ok.

At the attached pcap file, the DLCX of the initial bridge endpoint happens at packet 1661 and again happens at packet 2138 but this is ok since the call ended. 

Please confirm if thats ok

[LCM_trace_Issue834.pcap.zip](https://github.com/RestComm/RestComm-Core/files/114300/LCM_trace_Issue834.pcap.zip)

**Comment by hrosa** [comment]
@gvagenas All MGCP commands seem correct to me, including cleanup process.
